apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: nginx
    image: ashfaqchougle/nonroot-nginx:latest
    command: [ "sh", "-c", "tail -f /dev/null"]
    ports:
    - containerPort: 80
  hostNetwork: true